language: node_js
node_js:
 - 0.12
notifications:
  email: false
  slack: inquisi:tN28qlf1uc3wVDVt0Uqvucha#frontend
install:
 - npm install
 - npm install -g bower-installer gulp
 - bower-installer
 - gulp buildLocal
script: npm run testOnce
after_success: 
 - gulp buildProd
 - git checkout prod
 - git add -A
 - git commit -am "$TRAVIS_COMMIT"
 - git push origin/prod
branches:
 only:
  - master
cache:
  directories:
  - ./node_modules
  - ./bower_components