language: node_js
node_js:
 - 0.12
notifications:
  email: false
  slack: inquisi:tN28qlf1uc3wVDVt0Uqvucha#frontend
install:
 - npm install
 - npm install -g bower-installer gulp
 - bower-installer
 - gulp buildProd
script: npm run testOnce
after_success: pushToProdBranch.sh